Models/AddressModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Rozdzial3_C.Models
{
    public class AddressModel
    {
        public int ID { get; set; }
        [Required]
        public string Street { get; set; }
        [Required]
        public string PostalCode { get; set; }
        [Required]
        public string City { get; set; }

        [ForeignKey("ID")]
        public CustomerModel Customer { get; set; }
    }
}

Models/ConsultationModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Rozdzial3_C.Models
{
    [Table("Consultations")]
    public class ConsultationModel
    {
        public int ID { get; set; }
        [Required]
        public string Subject { get; set; }
        public string Description { get; set; }

        [ForeignKey("CustomerID")]
        public CustomerModel Customer { get; set; }

        public int CustomerID { get; set; }
    }
}

Models/CustomerModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Rozdzial3_C.Models
{
    public class CustomerModel
    {
        public int ID { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        public int Age { get; set; }
        public DateTime DateAdded { get; set; }
        public DateTime? DateUpdated { get; set; }

        public AddressModel Address { get; set; }
        public ICollection<ConsultationModel> Consultations { get; set; }
        public ICollection<TransactionModel> Transactions { get; set; }
    }
}

Models/ProductModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Rozdzial3_C.Models
{
    public class ProductModel
    {
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public ICollection<TransactionModel> Transactions { get; set; }
    }
}

Models/TransactionModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Rozdzial3_C.Models
{
    public class TransactionModel
    {
        public int ID { get; set; }
        public DateTime Date { get; set; }

        public int CustomerID { get; set; }

        [ForeignKey("CustomerID")]
        public CustomerModel Customer { get; set; }

        public int ProductID { get; set; }
        [ForeignKey("ProductID")]
        public ProductModel Product { get; set; }
    }
}

Controllers/ConsultationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rozdzial3_C.Models;

namespace Rozdzial3_C.Controllers
{
    public class ConsultationController : Controller
    {
        private readonly EFCDbContext Context;

        public ConsultationController(EFCDbContext context)
        {
            this.Context = context;
        }

        public IActionResult Index(int id)
        {
            var customer = Context.Customers.Include(x => x.Consultations).Single(x => x.ID == id);
            return View(customer);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(int id, [FromForm] ConsultationModel consult)
        {
            consult.CustomerID = id;
            if (ModelState.IsValid)
            {
                Context.Add<ConsultationModel>(consult);
                Context.SaveChanges();
                return RedirectToAction("Index", new { id });
            }

            return View(consult);
        }
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rozdzial3_C.Models;

namespace Rozdzial3_C.Controllers
{
    public class CustomerController : Controller
    {
        private readonly EFCDbContext Context;

        public CustomerController(EFCDbContext context)
        {
            this.Context = context;
        }

        public IActionResult Index()
        {
            var customers = Context.Customers.Include(x => x.Address).ToList();
            //var customers = Context.Customers.ToList();
            return View(customers);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(CustomerModel customer)
        {
            customer.DateAdded = DateTime.Now;

            if (ModelState.IsValid)
            {
                Context.Customers.Add(customer);
                Context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        public IActionResult Detail(int id)
        {
            var customer = Context.Customers.Include(x => x.Address).Single(x => x.ID == id);
            return View(customer);
        }
    }
}

Views/Consultation/Add.cshtml
@model ConsultationModel

<h1>Nowa konsultacja</h1>

@using (Html.BeginForm("Add", "Consultation", FormMethod.Post))
{
    @Html.LabelFor(x => x.Subject)
    @Html.TextBoxFor(x => x.Subject)
    <br />
    @Html.LabelFor(x => x.Description)
    @Html.TextAreaFor(x => x.Description)
    <br />

    <button>Dodaj</button>

    @Html.ValidationSummary()
}

Views/Consultation/Index.cshtml
@model CustomerModel

<h1>Konsultacje klienta @Model.FirstName @Model.LastName</h1>

<table>
    <tr>
        <td>ID</td>
        <td>Temat</td>
        <td>Opis</td>
    </tr>
    @foreach (var consultation in Model.Consultations)
    {
        <tr>
            <td>@consultation.ID</td>
            <td>@consultation.Subject</td>
            <td>@consultation.Description</td>
        </tr>
    }
</table>

Views/Customer/Add.cshtml
@model CustomerModel

<h1>Nowy klient</h1>

@using (Html.BeginForm("Add", "Customer", FormMethod.Post))
{
    @Html.LabelFor(x => x.FirstName)
    @Html.TextBoxFor(x => x.FirstName)
    <br />
    @Html.LabelFor(x => x.LastName)
    @Html.TextBoxFor(x => x.LastName)
    <br />
    @Html.LabelFor(x => x.Age)
    @Html.TextBoxFor(x => x.Age)
    <br />

    @Html.LabelFor(x => x.Address.Street)
    @Html.TextBoxFor(x => x.Address.Street)
    <br />

    @Html.LabelFor(x => x.Address.PostalCode)
    @Html.TextBoxFor(x => x.Address.PostalCode)
    <br />

    @Html.LabelFor(x => x.Address.City)
    @Html.TextBoxFor(x => x.Address.City)
    <br />

    <button>Dodaj</button>

    @Html.ValidationSummary()
}

Views/Customer/Detail.cshtml
@model CustomerModel

<h1>Dane klienta @Model.ID</h1>

<table>
    <tr>
        <td>Imię i nazwisko:</td>
        <td>@Model.FirstName @Model.LastName</td>
    </tr>
    <tr>
        <td>Wiek:</td>
        <td>@Model.Age</td>
    </tr>
    <tr>
        <td>Ulica:</td>
        <td>@Model.Address?.Street</td>
    </tr>
    <tr>
        <td>Kod pocztowy i miasto:</td>
        <td>@Model.Address?.PostalCode @Model.Address?.City</td>
    </tr>
    <tr>
        <td>Data dodania:</td>
        <td>@Model.DateAdded</td>
    </tr>
    <tr>
        <td>Data aktualizacji:</td>
        <td>@Model.DateUpdated</td>
    </tr>
</table>

@Html.ActionLink("lista konsultacji", "Index", "Consultation", new { Model.ID })

Views/Customer/Index.cshtml
@model List<CustomerModel>

<h1>Lista klientów</h1>

<table>
    <tr>
        <td>ID</td>
        <td>Imię i nazwisko</td>
        <td>Wiek</td>
        <td>Adres</td>
        <td>Data dodania</td>
        <td>Data aktualizacji</td>
        <td>Akcje</td>
    </tr>
    @foreach (var customer in Model)
    {
        <tr>
            <td>@customer.ID</td>
            <td>@customer.FirstName @customer.LastName</td>
            <td>@customer.Age</td>
            <td>@customer.Address?.Street, @customer.Address?.PostalCode @customer.Address?.City</td>
            <td>@customer.DateAdded</td>
            <td>@customer.DateUpdated</td>
            <td>
                @Html.ActionLink("szczegóły", "Detail", "Customer", new { @customer.ID })
                @Html.ActionLink("konsultacje", "Index", "Consultation", new { @customer.ID })
            </td>
        </tr>
    }
</table>

@Html.ActionLink("dodaj klienta", "Add", "Customer")

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CRM</title>
</head>
<body>
    @RenderBody()
</body>
</html>